# Site settings
title: Дополнительные материалы к курсу Фотомама
email: minaeva.school@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Этот сайт содержит ответы на часто задаваемые вопросы
  к курсу Фотомама
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://minaeva.github.io" # the base hostname & protocol for your site
#twitter_username: minaeva
github_username:  minaeva

# Build settings
markdown: kramdown
permalink: none

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
