# Site settings
title: Дополнительные материалы к курсу Фотомама
email: minaeva.school@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Этот сайт содеожит ответы на часто задаваемые вопросы
  к курсу Фотомама
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://minaeva.github.io" # the base hostname & protocol for your site
#twitter_username: minaeva
github_username:  minaeva

# Build settings
markdown: kramdown
permalink: none

#prose.io config
prose:
  metadata:
    _posts:
      - name: "tags"
        field:
          element: "select"
          label: "Tags"
          options:
            - name: 'Tech'
              value: 'tech'
            - name: 'NONTech'
              value: 'nontech'
